apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: loadimpact/k6:latest
          command:
            - k6
            - run
            - /test/script.js
          volumeMounts:
            - name: k6-test
              mountPath: /test
      restartPolicy: Never
      volumes:
        - name: k6-test
          configMap:
            name: k6-test-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    
    export let options = {
      stages: [
        { duration: '30s', target: 20 },  // Ramp up to 20 users over 30s
        { duration: '1m', target: 20 },   // Stay at 20 users for 1 minute
        { duration: '30s', target: 0 },   // Ramp down to 0 users over 30s
      ],
    };
    
    export default function () {
      let res = http.get('http://zero-downtime-app.app-staging.svc.cluster.local');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(1);
    }