apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash
  labels:
    app: unleash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
    spec:
      containers:
        - name: unleash
          image: unleashorg/unleash-server:latest
          ports:
            - containerPort: 4242
          env:
            - name: DATABASE_URL
              value: "postgres://unleash_user:password@postgres:5432/unleash"
            - name: DATABASE_SSL
              value: "false"
            - name: LOG_LEVEL
              value: "info"
          readinessProbe:
            httpGet:
              path: /health
              port: 4242
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4242
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: unleash
  labels:
    app: unleash
spec:
  ports:
    - port: 4242
      targetPort: 4242
  selector:
    app: unleash